version: '3.4'

networks:
  nat:
    external:
      name: cmc
services:
  redis:
    image: redis:latest
    command: [ "redis-server", "/redis.conf" ]
    hostname: redis
    container_name: redis
    environment: 
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /u01/docker/infrastructures/redis/redis.conf:/redis.conf
      - /u01/data/redis/data:/data
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6379:6379"
    networks:
      - nat