version: '3.3'



volumes:
  redis:

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - daint-network-system

networks:
  daint-network-system:
    driver: bridge