version: '3.3'

networks:
  default:
    name: daint-network
    external: true

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - /mnt/d/daint/redis:/data
    ports:
      - "6379:6379"
    networks:
      - default