version: '3.3'

volumes:
  redis:

networks:
  default:
    external:
      name: daint-network

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - default