version: '3.3'

networks:
  default:
    name: daint-network
    external: true

services:
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always
    volumes:
      - /home/neo4j:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - default