version: '3.3'

networks:
  default:
    name: daint-network
    external: true
      

services:
  postgre:
    image: postgres
    restart: always
    hostname: postgre
    container_name: postgre
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Davidkmhd!1
    volumes:
      - /home/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default