version: '3.3'

networks:
  default:
    name: daint-network
    external: true

volumes:
  postgre:

services:
  postgre:
    image: postgres:latest
    restart: always
    hostname: postgre
    container_name: postgre
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Davidkmhd!1
    volumes:
      - postgre:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default