version: '3.3'
volumes:
  nexus-data:
services:
  nexus:
    image: 10.162.80.114:5000/sonatype/nexus3:3.42.0
    restart: always
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"