version: '3.3'
volumes:
  nexus-data:
services:
  nexus:
    image: sonatype/nexus3:latest
    restart: always
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"