version: '3.3'

networks:
  default:
    name: daint-network
    external: true

services:
  nexus:
    image: sonatype/nexus3:latest
    restart: always
    volumes:
      - /mnt/d/daint/nexus:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - default