# fly.toml file generated for empty-darkness-8835 on 2023-04-12T00:12:53+07:00

app = "empty-darkness-8835"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sin"
processes = []

[build]
  image = "davidngo1704/api-gateway:latest"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[mounts]
source="api_gateway_data"
destination="/location-root"