# fly.toml file generated for quiet-shape-605 on 2023-04-11T22:39:06+07:00

app = "quiet-shape-605"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sin"
processes = []

[build]
  image = "davidngo1704/task:latest"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[mounts]
source="task_data"
destination="/location-root"