version: '3.4'

volumes:
  rabbitmq:
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    restart: always
    hostname: rabbitmq
    container_name: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Davidkmhd!1
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"