version: '3.4'

services:
  rabbitmq:
    image: 10.162.80.114:5000/rabbitmq:3.8.9-management
    restart: always
    hostname: rabbitmq
    container_name: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Davidkmhd!1
    volumes:
      - /u01/data/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"