version: '3.3'

networks:
  default:
    name: daint-network
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    container_name: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Davidkmhd!1
      - RABBITMQ_DEFAULT_VHOST=daint
    volumes:
      - /mnt/d/daint/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default