version: '3.8'

networks:
  default:
    name: daint-network
    external: true

services:
  registry:
    container_name: registry
    image: registry:latest
    restart: always
    volumes:
      - /home/data/registry:/var/lib/registry
    ports:
      - "5000:5000"
    networks:
      - default